### ISSUE TITLE
How can I import this without webpack config? (i.e, in a create-react-app context)

### ISSUE THREAD

**Issue by 8bit-echo** [superRaytin/react-monaco-editor#143]
When using create-react-app or create-react-native-app, I can't use this component without ejecting and manually configuring the build tools. Is there a way around this?

**Comment by domoritz** [comment]
Yes, I think so. You'll have to manually add the right imports, though. Check the Monaco instructions. I don't have an example. If you have one, please share it here.

**Comment by kbuechl** [comment]
I found [this blog post](https://medium.com/@haugboelle/short-guide-to-using-monaco-with-create-react-app-26a1acad8ebe) that I follows. Change all the urls to reference the latest version of monaco though (14.3 at the time of this comment). 

I am having a few styling issues at the moment but it may be caused by the css framework I am using.
