### ISSUE TITLE
Support for DiffEditor

### ISSUE THREAD

**Issue by JeffSteinbok** [superRaytin/react-monaco-editor#32]
Do you have plans to support the Monaco DiffEditor?

**Comment by domoritz** [comment]
Can you describe what would have to be added?

**Comment by solemnify** [comment]
@domoritz 

Instead of creating a "base" monaco editor, react-monaco-editor will need to create a diff editor.

`
  initMonaco() {
...
      this.editor = context.monaco.editor.create(containerElement, {
        value,
        language,
        ...options,
      });
...
  }
`

initMonaco() will need to call the following function instead:

`monaco.editor.createDiffEditor(document.getElementById("container"), ...`

Refer to [https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-multi-line-example](url) for an example.

So the wrapper would most likely need to expose a prop for the editor "type" and react according to the initial value + changes.

**Comment by domoritz** [comment]
Thank you for the explanation @solemnify! I think this would be a great addition. However, I wonder why Microsoft decided to have two different constructors. do the arguments differ? If yes, then we should probably have two separate classes. If not, I would go with your proposal to add a type argument and choose the constructor accordingly. 

I won't have time to implement this but I am happy to review a pr with an example.

**Comment by mattmichler** [comment]
I have done a first pass at getting the diff editor implemented but don't feel comfortable making a pull request for a few reasons, I haven't thoroughly educated myself on Monaco, haven't thoroughly tested the code and I haven't refactored to reduce code duplication. But I thought I would post here in case anyone else is interested in continuing the work. A diff of the components is available in the comments of the gist: https://gist.github.com/mattmichler/2afef12fa6333489d4cad1ae9085ccaf

**Comment by expobrain** [comment]
I prefer to have two separate component for the editor and the diff editor as the original editor for consistency

**Comment by mattmichler** [comment]
Two components seems like the right call as the options and events are different between the two in the Monaco API.
