### ISSUE TITLE
ctrl+z doesn't undo

### ISSUE THREAD

**Issue by luisrudge** [superRaytin/react-monaco-editor#9]

**Comment by mathisonian** [comment]
I'm having this issue as well, any idea why? Happy to PR if anyone can point me in the right direction

**Comment by broken-e** [comment]
I've noticed this as well, and it only seems to occur when using `props.value` instead of `props.defaultValue`. I believe the culprit is the call to [`this.editor.setValue(nextProps.value)`](https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.js#L19) inside the `componentWillUpdate` method. It looks like the Monaco editor wipes out the undo history when setting the value on it.

My workaround is to set the initial value with `props.defaultValue` instead of `props.value`.

**Comment by luisrudge** [comment]
@superRaytin any thoughts on this fix?

**Comment by superRaytin** [comment]
Sorry for late and thank @2betop for the PR. I just published `0.7.1` for this issue @luisrudge

**Comment by luisrudge** [comment]
❤️
